### ISSUE TITLE
Could you add some training details in readme.md?

### ISSUE THREAD

**Issue by Wei-i** [ptirupat/MLAD#2]
Hi, thanks for your great work and source code！
I am sorry to disturb you for my poor  code ability  and  not  familiar with the field of `temporal action localization`.

Could you add more details in `readme.md`? 
For example, How should we `train` the model , `eval` the model or `visulize` the qualitative results or how to  store the `path of the dataset`？

I would be grateful if you could reply to me!
Thanks~

**Comment by ptirupat** [comment]
Hello, thank you for your interest in our work. I have added the sample command to run the training code in the readme file. This command will run the training code which also includes evaluation of the model after every few epochs.

In the coming days, I will try to clean up my code for visualizing the results and update the repo.

**Comment by Wei-i** [comment]
Oh! Thanks for selfless sharing and quickly reply!  :）(#^.^#)
