### ISSUE TITLE
Can you provide a dataset download address

### ISSUE THREAD

**Issue by z965631** [ptirupat/MLAD#3]

**Comment by ptirupat** [comment]
Hello,

Here are the download links

Charades: https://prior.allenai.org/projects/charades
MultiTHUMOS: http://ai.stanford.edu/~syyeung/everymoment.html

**Comment by Wei-i** [comment]
Sorry, I am confused, the 'data' of the link, 'http://ai.stanford.edu/~syyeung/everymoment.html' you provided, only contains `annotations` folder, `class_list.txt` and `readme`. In addition, it does not contains the video data. How should I download the videos of MultiTHUMOS dataset corresponding to the annotations?
I would be grateful if you could give me some advice:)

**Comment by ptirupat** [comment]
The videos in the MultiTHUMOS dataset are from UCF101. You can download the videos from the following link.

https://www.crcv.ucf.edu/data/UCF101.php

**Comment by Wei-i** [comment]
Thanks:) I used to use COCO and ImageNet.  I know little about the video action datasets.
The paper uses the `untrimmed videos`. And I found that in `MLAD/src/configuration.py`, there are about `features` file , for example `../datasets/Multi-THUMOS/features/flow_val.h5'` . So, should I only download the validation data about  features:`Pre-computed low-level Features (Improved DTF [1]): [Download] (updated Jul. 30, 2014)`, or videos:`Temporal annotations of actions (videos of 20 classes): [Download] (updated Jul. 30, 2014)` , or more?

**Comment by Wei-i** [comment]
It seems that `UCF101 videos (zipped folder): [Download] (updated Jul. 27, 2014)` in traning data(13320 trimmed videos) does not use in your great work after I download this data.

**Comment by Saunak626** [comment]
> Hello,
> 
> Here are the download links
> 
> Charades: https://prior.allenai.org/projects/charades MultiTHUMOS: http://ai.stanford.edu/~syyeung/everymoment.html

[Annotations & Evaluation Code (3 MB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades.zip)
[Caption evaluation code (70 MB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/charades-caption.zip)
[Data (scaled to 480p, 13 GB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_480.zip)
[Data (original size) (55 GB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1.zip)
[RGB frames at 24fps (76 GB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_rgb.tar)
[Optical Flow at 24fps (45 GB)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_flow.tar)
[Two-Stream features at 8fps (RGB Stream, 12GB compressed, 37GB uncompressed)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_features_rgb.tar.gz)
[Two-Stream features at 8fps (Flow Stream, 16GB compressed, 45GB uncompressed)](https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_features_flow.tar.gz)

Hello, Which specific Charades dataset is used? What's its resolution?
