### ISSUE TITLE
can you provide the dataset feature download address

### ISSUE THREAD

**Issue by liuxingbin** [ptirupat/MLAD#4]
Hello!

Thanks for your marvorlous work, but I have some question about the input feature.  In paper, the feature are extracted by pretrained I3D model, and I found the I3D model in [github](https://github.com/piergiaj/pytorch-i3d). This repo only extracted the flow and rgb feature individually and  save them  in `.npy`  format, how the combined feature extracted?  Could you provide the feature download address.

Thank you!

**Comment by ptirupat** [comment]
I have updated the README with the link to the features file used for training the models.

**Comment by liuxingbin** [comment]
> I have updated the README with the link to the features file used for training the models.

Thanks, That will help me a lot.
