### ISSUE TITLE
About the cooccur_metric.py

### ISSUE THREAD

**Issue by jingyang2017** [ptirupat/MLAD#7]
Thanks for the great work and the proposed metrics are very useful.
https://github.com/ptirupat/MLAD/blob/d16f69d658abe5ab5b2b9d5dc46e7fb55f2e1024/src/cooccur_metric.py#L118
From my understading, the n_in_last_t always includes the current label, which makes -1 not exist. 
Is my understanding correct?

**Comment by Wyz2927** [comment]
> Thanks for the great work and the proposed metrics are very useful.
> 
> https://github.com/ptirupat/MLAD/blob/d16f69d658abe5ab5b2b9d5dc46e7fb55f2e1024/src/cooccur_metric.py#L118
> 
> 
> From my understading, the n_in_last_t always includes the current label, which makes -1 not exist.
> Is my understanding correct?

hello, have you reproduce the results in this paper? I try to train my own model with the given code but only get f-map 43.2% on multhumos. Do you have any advice? looking forward to your reply.

**Comment by jingyang2017** [comment]
> > Thanks for the great work and the proposed metrics are very useful.
> > https://github.com/ptirupat/MLAD/blob/d16f69d658abe5ab5b2b9d5dc46e7fb55f2e1024/src/cooccur_metric.py#L118
> > 
> > From my understading, the n_in_last_t always includes the current label, which makes -1 not exist.
> > Is my understanding correct?
> 
> hello, have you reproduce the results in this paper? I try to train my own model with the given code but only get f-map 43.2% on multhumos. Do you have any advice? looking forward to your reply.

I only use this metric in other task without reprocucing the results in this paper.

**Comment by ptirupat** [comment]
n_in_last_t does not include the current timestep
