### ISSUE TITLE
Link for downloading multithumos does not existed

### ISSUE THREAD

**Issue by TuanTNG** [ptirupat/MLAD#9]
Hi, 

Thank you for your awesome work.
Can you please update the downloaded link for Multithumos feature? The following link you provided in the readme is no longer work: https://drive.google.com/drive/folders/1txv4OyMd88ku3nzWAeYVhJ-9YR8NHE8w?usp=sharing

**Comment by blank-Cd** [comment]
yes ,same question

**Comment by andypinxinliu** [comment]
Hi, there a new link for the extracted features?

**Comment by ptirupat** [comment]
Hello, I have fixed the link. Sorry for the delay.
